name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Runtime
        run: node --version
      - name: Syntax
        run: npm run check
      - name: Tests
        run: npm test
