const $=s=>document.querySelector(s), base=location.pathname.replace(/\/$/,'')+'/api';let csrf='',editing=null,routeCache=[];
async function call(p,o={}){o.headers={'content-type':'application/json',...(csrf?{'x-csrf-token':csrf}:{}),...(o.headers||{})};const r=await fetch(base+p,o),j=await r.json();if(!r.ok)throw Error(j.error||'请求失败');return j}
function msg(v){$('#gate-msg').textContent=v||''}function val(s){return $(s).value}function bool(s){return val(s)==='true'}
async function start(){try{const s=await call('/status');$('#gate').classList.remove('hidden');$(s.initialized?'#login':'#setup').classList.remove('hidden')}catch(e){msg(e.message)}}
$('#setup-btn').onclick=async()=>{try{const j=await call('/setup',{method:'POST',body:JSON.stringify({username:val('#su-user'),password:val('#su-pass'),setupToken:val('#su-token')})});$('#secret').textContent=`TOTP Secret: ${j.secret}\n\n恢复码（每行一个）：\n${j.recovery.join('\n')}\n\n配置 URI：\n${j.totpUri}`;$('#modal').classList.remove('hidden');$('#setup').classList.add('hidden');$('#login').classList.remove('hidden')}catch(e){msg(e.message)}};
$('#login-btn').onclick=async()=>{try{const j=await call('/login',{method:'POST',body:JSON.stringify({password:val('#password'),code:val('#code')})});csrf=j.csrf;$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');$('#nav').classList.remove('hidden');await routes()}catch(e){msg(e.message)}};
function badge(text){const e=document.createElement('span');e.className='pill';e.textContent=text;return e}
async function routes(){const j=await call('/routes');routeCache=j.routes;$('#routes').innerHTML='';for(const r of j.routes){const d=document.createElement('div');d.className='route';const left=document.createElement('div'),middle=document.createElement('div'),actions=document.createElement('div');actions.className='actions';const name=document.createElement('strong'),code=document.createElement('code'),info=document.createElement('div'),toggle=document.createElement('button'),edit=document.createElement('button'),rot=document.createElement('button'),del=document.createElement('button');name.textContent=r.name;code.textContent=r.accessMode==='alias_only'?`/${r.alias}/`:`/${r.alias}/••••••/`;info.append(badge(r.enabled?'启用':'停用'),badge(`主线路 ${r.upstreams.length}`),badge(r.playbackUpstreams.length?`播放线路 ${r.playbackUpstreams.length}`:'统一上游'),badge(r.directStream?'302 直连':'302 中转'),badge(r.clientProfile.enabled?'兼容头开启':'原始客户端头'));toggle.textContent=r.enabled?'停用':'启用';edit.textContent='编辑';rot.textContent='轮换密钥';rot.disabled=r.accessMode==='alias_only';del.textContent='删除';del.className='danger';toggle.onclick=async()=>{await call(`/routes/${r.id}`,{method:'PATCH',body:JSON.stringify({enabled:!r.enabled})});await routes()};edit.onclick=()=>editRoute(r);rot.onclick=async()=>showSecret(await call(`/routes/${r.id}/rotate-key`,{method:'POST',body:'{}'}));del.onclick=async()=>{if(confirm(`删除 ${r.name}？`)){await call(`/routes/${r.id}`,{method:'DELETE'});await routes()}};left.append(name,code);middle.append(info);actions.append(toggle,edit,rot,del);d.append(left,middle,actions);$('#routes').append(d)}}
function formData(){return{name:val('#name'),alias:val('#alias'),upstreams:val('#upstreams'),playbackUpstreams:val('#playback-upstreams'),accessMode:val('#access-mode'),directStream:bool('#direct-stream'),allowPrivate:bool('#private'),tlsVerify:bool('#tls'),showOnHome:bool('#show-home'),clientProfile:{enabled:bool('#profile-enabled'),userAgent:val('#profile-ua'),client:val('#profile-client'),deviceName:val('#profile-device'),deviceId:val('#profile-device-id')}}}
function setVal(s,v){$(s).value=v??''}function editRoute(r){editing=r.id;$('#form-title').textContent=`编辑节点：${r.name}`;setVal('#name',r.name);setVal('#alias',r.alias);setVal('#upstreams',r.upstreams.join('\n'));setVal('#playback-upstreams',r.playbackUpstreams.join('\n'));setVal('#access-mode',r.accessMode);$('#access-mode').disabled=true;setVal('#direct-stream',String(r.directStream));setVal('#private',String(r.allowPrivate));setVal('#tls',String(r.tlsVerify));setVal('#show-home',String(r.showOnHome));setVal('#profile-enabled',String(r.clientProfile.enabled));setVal('#profile-ua',r.clientProfile.userAgent);setVal('#profile-client',r.clientProfile.client);setVal('#profile-device',r.clientProfile.deviceName);setVal('#profile-device-id',r.clientProfile.deviceId);$('#add').textContent='保存修改';$('#cancel-edit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function resetForm(){editing=null;$('#form-title').textContent='新增 Emby 节点';for(const s of ['#name','#alias','#upstreams','#playback-upstreams','#profile-ua','#profile-client','#profile-device','#profile-device-id'])setVal(s,'');for(const s of ['#private','#show-home','#profile-enabled','#direct-stream'])setVal(s,'false');setVal('#tls','true');setVal('#access-mode','key');$('#access-mode').disabled=false;$('#add').textContent='创建节点';$('#cancel-edit').classList.add('hidden')}
function showSecret(x){$('#secret').textContent=x.accessKey?`客户端路径：\n${x.clientPath}\n\n访问密钥：\n${x.accessKey}`:`客户端路径：\n${x.clientPath}\n\n该节点未启用访问密钥。`;$('#modal').classList.remove('hidden')}
$('#add').onclick=async()=>{try{const data=formData();if(editing){delete data.accessMode;await call(`/routes/${editing}`,{method:'PATCH',body:JSON.stringify(data)});resetForm()}else showSecret(await call('/routes',{method:'POST',body:JSON.stringify(data)}));await routes()}catch(e){alert(e.message)}};
$('#cancel-edit').onclick=resetForm;$('#close-modal').onclick=()=>$('#modal').classList.add('hidden');$('#logout').onclick=async()=>{await call('/logout',{method:'POST',body:'{}'});location.reload()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{const p=b.dataset.page;for(const name of ['routes','diagnostics','audit'])$(`#${name}-page`).classList.toggle('hidden',p!==name);if(p==='audit'){const j=await call('/audit');$('#audit').textContent=j.audit.map(x=>`${x.at}  ${x.action}  ${x.ip}  ${x.detail}`).join('\n')}if(p==='diagnostics'){const j=await call('/diagnostics');$('#diagnostics').textContent=j.nodes.map(n=>`${n.alias}\n${n.upstreams.map((u,i)=>`  线路 ${i+1}: ${u.circuitOpen?'熔断':'可用'} | 连续失败 ${u.failures} | 最近成功 ${u.lastSuccess||'-'} | ${u.lastError||''}`).join('\n')}`).join('\n\n')}});start();
